var searchData=
[
  ['s_20ip_20address_20with _20set_5fip_5faddress_0',['Set user&apos;s IP address with &quot;set_ip_address&quot;',['../md_docs_203-adding-data.html#autotoc_md30',1,'']]],
  ['screen_20resolution_20with _20set_5fscreen_5fresolution_1',['Set screen resolution with &quot;set_screen_resolution&quot;',['../md_docs_203-adding-data.html#autotoc_md24',1,'']]],
  ['screen_20views_20with _20screenviewevent_2',['Track screen views with &quot;ScreenViewEvent&quot;',['../md_docs_204-tracking-events.html#autotoc_md35',1,'']]],
  ['screenviewevent_3',['Track screen views with &quot;ScreenViewEvent&quot;',['../md_docs_204-tracking-events.html#autotoc_md35',1,'']]],
  ['selfdescribing_20unstructured_20events_20with _20selfdescribingevent_4',['Track SelfDescribing/Unstructured events with &quot;SelfDescribingEvent&quot;',['../md_docs_204-tracking-events.html#autotoc_md34',1,'']]],
  ['selfdescribingevent_5',['Track SelfDescribing/Unstructured events with &quot;SelfDescribingEvent&quot;',['../md_docs_204-tracking-events.html#autotoc_md34',1,'']]],
  ['session_6',['Client session',['../md_docs_202-initialisation.html#autotoc_md20',1,'']]],
  ['session_20configuration_20using_20sessionconfiguration_7',['Session configuration using &quot;SessionConfiguration&quot;',['../md_docs_202-initialisation.html#autotoc_md15',1,'']]],
  ['session_20store_8',['Session store',['../md_docs_206-client-sessions.html#autotoc_md46',1,'']]],
  ['sessionconfiguration_9',['Session configuration using &quot;SessionConfiguration&quot;',['../md_docs_202-initialisation.html#autotoc_md15',1,'']]],
  ['sessions_10',['Client Sessions',['../md_docs_206-client-sessions.html',1,'']]],
  ['set_20color_20depth_20with _20tt_20set_5fcolor_5fdepth_20tt_20set_20color_20depth_20with_20set_5fcolor_5fdepth_11',['Set color depth with &lt;tt&gt;set_color_depth&lt;/tt&gt;[](#set-color-depth-with-set_color_depth)',['../md_docs_203-adding-data.html#autotoc_md26',1,'']]],
  ['set_20color_20depth_20with_20set_5fcolor_5fdepth_12',['Set color depth with &lt;tt&gt;set_color_depth&lt;/tt&gt;[](#set-color-depth-with-set_color_depth)',['../md_docs_203-adding-data.html#autotoc_md26',1,'']]],
  ['set_20custom_20user_20agent_20with _20set_5fuseragent_13',['Set custom user-agent with &quot;set_useragent&quot;',['../md_docs_203-adding-data.html#autotoc_md29',1,'']]],
  ['set_20screen_20resolution_20with _20set_5fscreen_5fresolution_14',['Set screen resolution with &quot;set_screen_resolution&quot;',['../md_docs_203-adding-data.html#autotoc_md24',1,'']]],
  ['set_20the_20language_20with _20tt_20set_5flanguage_20tt_20set_20the_20language_20with_20set_5flanguage_15',['Set the language with &lt;tt&gt;set_language&lt;/tt&gt;[](#set-the-language-with-set_language)',['../md_docs_203-adding-data.html#autotoc_md28',1,'']]],
  ['set_20the_20language_20with_20set_5flanguage_16',['Set the language with &lt;tt&gt;set_language&lt;/tt&gt;[](#set-the-language-with-set_language)',['../md_docs_203-adding-data.html#autotoc_md28',1,'']]],
  ['set_20timezone_20with _20set_5ftimezone_17',['Set timezone with &quot;set_timezone&quot;',['../md_docs_203-adding-data.html#autotoc_md27',1,'']]],
  ['set_20user_20id_20with _20set_5fuser_5fid_18',['Set user ID with &quot;set_user_id&quot;',['../md_docs_203-adding-data.html#autotoc_md23',1,'']]],
  ['set_20user_20s_20ip_20address_20with _20set_5fip_5faddress_19',['Set user&apos;s IP address with &quot;set_ip_address&quot;',['../md_docs_203-adding-data.html#autotoc_md30',1,'']]],
  ['set_20viewport_20dimensions_20with _20tt_20set_5fviewport_20tt_20set_20viewport_20dimensions_20with_20set_5fviewport_20',['Set viewport dimensions with &lt;tt&gt;set_viewport&lt;/tt&gt;[](#set-viewport-dimensions-with-set_viewport)',['../md_docs_203-adding-data.html#autotoc_md25',1,'']]],
  ['set_20viewport_20dimensions_20with_20set_5fviewport_21',['Set viewport dimensions with &lt;tt&gt;set_viewport&lt;/tt&gt;[](#set-viewport-dimensions-with-set_viewport)',['../md_docs_203-adding-data.html#autotoc_md25',1,'']]],
  ['set_5fcolor_5fdepth_20tt_20set_20color_20depth_20with_20set_5fcolor_5fdepth_22',['Set color depth with &lt;tt&gt;set_color_depth&lt;/tt&gt;[](#set-color-depth-with-set_color_depth)',['../md_docs_203-adding-data.html#autotoc_md26',1,'']]],
  ['set_5fip_5faddress_23',['Set user&apos;s IP address with &quot;set_ip_address&quot;',['../md_docs_203-adding-data.html#autotoc_md30',1,'']]],
  ['set_5flanguage_20tt_20set_20the_20language_20with_20set_5flanguage_24',['Set the language with &lt;tt&gt;set_language&lt;/tt&gt;[](#set-the-language-with-set_language)',['../md_docs_203-adding-data.html#autotoc_md28',1,'']]],
  ['set_5fscreen_5fresolution_25',['Set screen resolution with &quot;set_screen_resolution&quot;',['../md_docs_203-adding-data.html#autotoc_md24',1,'']]],
  ['set_5ftimezone_26',['Set timezone with &quot;set_timezone&quot;',['../md_docs_203-adding-data.html#autotoc_md27',1,'']]],
  ['set_5fuser_5fid_27',['Set user ID with &quot;set_user_id&quot;',['../md_docs_203-adding-data.html#autotoc_md23',1,'']]],
  ['set_5fuseragent_28',['Set custom user-agent with &quot;set_useragent&quot;',['../md_docs_203-adding-data.html#autotoc_md29',1,'']]],
  ['set_5fviewport_20tt_20set_20viewport_20dimensions_20with_20set_5fviewport_29',['Set viewport dimensions with &lt;tt&gt;set_viewport&lt;/tt&gt;[](#set-viewport-dimensions-with-set_viewport)',['../md_docs_203-adding-data.html#autotoc_md25',1,'']]],
  ['setup_30',['Setup',['../md_docs_201-setup.html',1,'']]],
  ['snowplow_20interface_31',['snowplow interface',['../md_docs_202-initialisation.html#autotoc_md10',1,'Option 1: Creating a tracker with default configuration using the &quot;Snowplow&quot; interface'],['../md_docs_202-initialisation.html#autotoc_md11',1,'Option 2: Creating a tracker with custom configuration using the &quot;Snowplow&quot; interface']]],
  ['specific_20events_32',['Tracking specific events',['../md_docs_204-tracking-events.html',1,'']]],
  ['storage_33',['Storage',['../md_docs_202-initialisation.html#autotoc_md17',1,'']]],
  ['store_34',['store',['../md_docs_205-emitters.html#autotoc_md39',1,'Event store'],['../md_docs_206-client-sessions.html#autotoc_md46',1,'Session store']]],
  ['structured_20events_20with _20tt_20structuredevent_20tt_20track_20structured_20events_20with_20trackstructevent_35',['Track structured events with &lt;tt&gt;StructuredEvent&lt;/tt&gt;[](#track-structured-events-with-trackstructevent)',['../md_docs_204-tracking-events.html#autotoc_md36',1,'']]],
  ['structuredevent_20tt_20track_20structured_20events_20with_20trackstructevent_36',['Track structured events with &lt;tt&gt;StructuredEvent&lt;/tt&gt;[](#track-structured-events-with-trackstructevent)',['../md_docs_204-tracking-events.html#autotoc_md36',1,'']]],
  ['subdirectory_20in_20your_20cmake_20project_37',['As a subdirectory in your CMake project',['../md_docs_201-setup.html#autotoc_md5',1,'']]],
  ['subject_38',['Subject',['../md_docs_202-initialisation.html#autotoc_md19',1,'']]],
  ['subject_20class_39',['Adding extra data: the Subject class',['../md_docs_203-adding-data.html',1,'']]]
];
