var searchData=
[
  ['target_20in_20your_20cmake_20project_0',['As an imported target in your CMake project',['../md_docs_201-setup.html#autotoc_md4',1,'']]],
  ['the_20language_20with _20tt_20set_5flanguage_20tt_20set_20the_20language_20with_20set_5flanguage_1',['Set the language with &lt;tt&gt;set_language&lt;/tt&gt;[](#set-the-language-with-set_language)',['../md_docs_203-adding-data.html#autotoc_md28',1,'']]],
  ['the_20library_2',['Import the library',['../md_docs_202-initialisation.html#autotoc_md9',1,'']]],
  ['the_20snowplow_20interface_3',['the snowplow interface',['../md_docs_202-initialisation.html#autotoc_md10',1,'Option 1: Creating a tracker with default configuration using the &quot;Snowplow&quot; interface'],['../md_docs_202-initialisation.html#autotoc_md11',1,'Option 2: Creating a tracker with custom configuration using the &quot;Snowplow&quot; interface']]],
  ['the_20subject_20class_4',['Adding extra data: the Subject class',['../md_docs_203-adding-data.html',1,'']]],
  ['timestamp_20argument_5',['Optional true-timestamp argument',['../md_docs_204-tracking-events.html#autotoc_md33',1,'']]],
  ['timezone_20with _20set_5ftimezone_6',['Set timezone with &quot;set_timezone&quot;',['../md_docs_203-adding-data.html#autotoc_md27',1,'']]],
  ['timing_20events_20with _20timingevent_7',['Track timing events with &quot;TimingEvent&quot;',['../md_docs_204-tracking-events.html#autotoc_md37',1,'']]],
  ['timingevent_8',['Track timing events with &quot;TimingEvent&quot;',['../md_docs_204-tracking-events.html#autotoc_md37',1,'']]],
  ['to_20newer_20versions_9',['Upgrading to Newer Versions',['../md_docs_207-upgrading.html',1,'']]],
  ['to_20v0_202_200_10',['Upgrading to v0.2.0',['../md_docs_207-upgrading.html#autotoc_md51',1,'']]],
  ['to_20v0_203_200_11',['Upgrading to v0.3.0',['../md_docs_207-upgrading.html#autotoc_md50',1,'']]],
  ['to_20v1_200_200_12',['Upgrading to v1.0.0',['../md_docs_207-upgrading.html#autotoc_md49',1,'']]],
  ['to_20v2_200_200_13',['Upgrading to v2.0.0',['../md_docs_207-upgrading.html#autotoc_md48',1,'']]],
  ['to_20your_20project_14',['Copying files to your project',['../md_docs_201-setup.html#autotoc_md6',1,'']]],
  ['track_20screen_20views_20with _20screenviewevent_15',['Track screen views with &quot;ScreenViewEvent&quot;',['../md_docs_204-tracking-events.html#autotoc_md35',1,'']]],
  ['track_20selfdescribing_20unstructured_20events_20with _20selfdescribingevent_16',['Track SelfDescribing/Unstructured events with &quot;SelfDescribingEvent&quot;',['../md_docs_204-tracking-events.html#autotoc_md34',1,'']]],
  ['track_20structured_20events_20with _20tt_20structuredevent_20tt_20track_20structured_20events_20with_20trackstructevent_17',['Track structured events with &lt;tt&gt;StructuredEvent&lt;/tt&gt;[](#track-structured-events-with-trackstructevent)',['../md_docs_204-tracking-events.html#autotoc_md36',1,'']]],
  ['track_20structured_20events_20with_20trackstructevent_18',['Track structured events with &lt;tt&gt;StructuredEvent&lt;/tt&gt;[](#track-structured-events-with-trackstructevent)',['../md_docs_204-tracking-events.html#autotoc_md36',1,'']]],
  ['track_20timing_20events_20with _20timingevent_19',['Track timing events with &quot;TimingEvent&quot;',['../md_docs_204-tracking-events.html#autotoc_md37',1,'']]],
  ['tracker_20',['tracker',['../index.html',1,'C++ Tracker'],['../md_docs_202-initialisation.html#autotoc_md21',1,'Tracker']]],
  ['tracker_20compatibility_21',['Tracker compatibility',['../md_docs_201-setup.html#autotoc_md2',1,'']]],
  ['tracker_20configuration_20using_20trackerconfiguration_22',['Tracker configuration using &quot;TrackerConfiguration&quot;',['../md_docs_202-initialisation.html#autotoc_md12',1,'']]],
  ['tracker_20emitter_20and_20clientsession_20directly_23',['Option 3: Managing &quot;Tracker&quot;, &quot;Emitter&quot;, and &quot;ClientSession&quot; directly',['../md_docs_202-initialisation.html#autotoc_md16',1,'']]],
  ['tracker_20with_20custom_20configuration_20using_20the_20snowplow_20interface_24',['Option 2: Creating a tracker with custom configuration using the &quot;Snowplow&quot; interface',['../md_docs_202-initialisation.html#autotoc_md11',1,'']]],
  ['tracker_20with_20default_20configuration_20using_20the_20snowplow_20interface_25',['Option 1: Creating a tracker with default configuration using the &quot;Snowplow&quot; interface',['../md_docs_202-initialisation.html#autotoc_md10',1,'']]],
  ['trackerconfiguration_26',['Tracker configuration using &quot;TrackerConfiguration&quot;',['../md_docs_202-initialisation.html#autotoc_md12',1,'']]],
  ['tracking_20specific_20events_27',['Tracking specific events',['../md_docs_204-tracking-events.html',1,'']]],
  ['trackstructevent_28',['Track structured events with &lt;tt&gt;StructuredEvent&lt;/tt&gt;[](#track-structured-events-with-trackstructevent)',['../md_docs_204-tracking-events.html#autotoc_md36',1,'']]],
  ['true_20timestamp_20argument_29',['Optional true-timestamp argument',['../md_docs_204-tracking-events.html#autotoc_md33',1,'']]],
  ['tt_20set_5fcolor_5fdepth_20tt_20set_20color_20depth_20with_20set_5fcolor_5fdepth_30',['Set color depth with &lt;tt&gt;set_color_depth&lt;/tt&gt;[](#set-color-depth-with-set_color_depth)',['../md_docs_203-adding-data.html#autotoc_md26',1,'']]],
  ['tt_20set_5flanguage_20tt_20set_20the_20language_20with_20set_5flanguage_31',['Set the language with &lt;tt&gt;set_language&lt;/tt&gt;[](#set-the-language-with-set_language)',['../md_docs_203-adding-data.html#autotoc_md28',1,'']]],
  ['tt_20set_5fviewport_20tt_20set_20viewport_20dimensions_20with_20set_5fviewport_32',['Set viewport dimensions with &lt;tt&gt;set_viewport&lt;/tt&gt;[](#set-viewport-dimensions-with-set_viewport)',['../md_docs_203-adding-data.html#autotoc_md25',1,'']]],
  ['tt_20structuredevent_20tt_20track_20structured_20events_20with_20trackstructevent_33',['Track structured events with &lt;tt&gt;StructuredEvent&lt;/tt&gt;[](#track-structured-events-with-trackstructevent)',['../md_docs_204-tracking-events.html#autotoc_md36',1,'']]]
];
