name: Documentation

on:
  push:
    tags:
    - '*.*.*'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get upgrade
          sudo apt-get install -y doxygen

      - name: Set version
        run: echo "PROJECT_NUMBER = `git describe --tags`" >> Doxyfile

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html/
